-- ===== SUPABASE TABLE UPDATE - quotes_and_inquiries =====
-- Run this SQL in Supabase to update your table with enhanced tracking

-- STEP 1: Run this FIRST - Add new columns to existing table
-- Copy and paste ONLY this section into Supabase SQL Editor and run:

ALTER TABLE quotes_and_inquiries ADD COLUMN IF NOT EXISTS device_id VARCHAR(100);
ALTER TABLE quotes_and_inquiries ADD COLUMN IF NOT EXISTS user_agent TEXT;
ALTER TABLE quotes_and_inquiries ADD COLUMN IF NOT EXISTS referrer TEXT;
ALTER TABLE quotes_and_inquiries ADD COLUMN IF NOT EXISTS page_url TEXT;
ALTER TABLE quotes_and_inquiries ADD COLUMN IF NOT EXISTS submission_ip VARCHAR(50);
ALTER TABLE quotes_and_inquiries ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'pending';

-- STEP 2: Run this SECOND - Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_quotes_device_id ON quotes_and_inquiries(device_id);
CREATE INDEX IF NOT EXISTS idx_quotes_status ON quotes_and_inquiries(status);

-- ===== OR IF TABLE DOESN'T EXIST, CREATE IT FRESH =====

-- CREATE TABLE quotes_and_inquiries (
--   id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--   name VARCHAR(255) NOT NULL,
--   email VARCHAR(255) NOT NULL,
--   phone VARCHAR(20) NOT NULL,
--   service VARCHAR(255),
--   message TEXT,
--   form_type VARCHAR(50) NOT NULL,
--   device_id VARCHAR(100),
--   user_agent TEXT,
--   referrer TEXT,
--   page_url TEXT,
--   submission_ip VARCHAR(50),
--   status VARCHAR(50) DEFAULT 'pending',
--   created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
--   updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
-- );

-- -- Create indexes
-- CREATE INDEX idx_quotes_email ON quotes_and_inquiries(email);
-- CREATE INDEX idx_quotes_created_at ON quotes_and_inquiries(created_at);
-- CREATE INDEX idx_quotes_device_id ON quotes_and_inquiries(device_id);
-- CREATE INDEX idx_quotes_status ON quotes_and_inquiries(status);
-- CREATE INDEX idx_quotes_form_type ON quotes_and_inquiries(form_type);

-- -- Enable Row Level Security (RLS)
-- ALTER TABLE quotes_and_inquiries ENABLE ROW LEVEL SECURITY;

-- -- Create policy to allow inserts from anonymous users
-- CREATE POLICY "Allow inserts from anyone" ON quotes_and_inquiries
--   FOR INSERT
--   WITH CHECK (TRUE);

-- -- Create policy to allow reads (optional, if you need to verify submission)
-- CREATE POLICY "Allow reads for testing" ON quotes_and_inquiries
--   FOR SELECT
--   USING (TRUE);

-- ===== END OF SQL =====
